kind: pipeline
type: aws
name: default

pool:
  use: ubuntu

steps:
  - name: env
    image: alpine:latest
    commands:
      - env | sort
  - name: build
    image: golang:latest
    commands:
      - go build
